# Generated by Django 2.2.12 on 2020-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=200)),
                ('amountRange', models.IntegerField(default=1)),
                ('time', models.IntegerField(default=1)),
                ('mode', models.IntegerField(default=1)),
                ('receiver', models.IntegerField(default=1)),
                ('location', models.IntegerField(default=1)),
                ('balancePercent', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=200)),
                ('modelId', models.CharField(max_length=150)),
            ],
        ),
    ]
