# Generated by Django 2.2.12 on 2020-05-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentsDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=200)),
                ('model', models.BinaryField()),
                ('modelRefData', models.BinaryField()),
                ('scalar', models.BinaryField()),
                ('pca', models.BinaryField()),
            ],
        ),
    ]
